### ISSUE TITLE
Feature: Allow admins to customize the look and feel with admin settings instead of just custom CSS

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#11]
The look and feel of Moodle themes always can be changed by writing custom CSS and adding this CSS to the theme's custom CSS setting.

However, to be able to reach your goal, you have to know which CSS selectors to use and you will have much fun writing and debugging your custom CSS.

As an alternative, the theme could provide admin settings to change some often needed UI parts in a direct and fail-safe way.
Boost Campus had some settings like that (for example for setting the width of the blocks column). Other themes like https://moodle.org/plugins/theme_fordson provide much more settings like that.

This issue is a place to discuss the needs and to identify real pain points which could then be solved afterwards.

**Comment by ralf-krause** [comment]
Yes, it would be nice to get a setting for the width of the block drawer. 

With Moodle 3.11 we were using the block column for some announcements and feedbacks. If you want to get anonymous feedback from people without an user account you need to put the feedback on the frontpage. I tested to upgrade the page to Moodle 4.0.2 and I got a lot of stupid text breaks. The reason for these breaks are the bigger modul icons and the smaller block width.
https://bildungsportal.magdeburg.de/moodle/
https://bildungsportal.magdeburg.de/moodle40/

Yes, we should get a new idea for the announcements and feedbacks because the block drawer normally is closed and the users can‘t see them.

Best regards,
Ralf

Ralf Krause
moodleSCHULE e.V.

**Comment by wiebkemueller-hsh** [comment]
Hi, thanks for this thread.

It would be great to give admins a tool to generally improve the identification of links for users (students) that occur within plain text, as most links that users (teachers) create by themselves appear within plain text. It is not so much about the links that are quite obvious and expected like those in navigation sections or on the course start page or dashboard, but in other environments, such as:

- Any activity plain text that uses the WYSIWIG Editor (be it Atto for now or the back-to-TinyMCE in future) e.g. forum, e.g. glossary entry, ...
- Activity description (the one that can be shown on the course start page or underneath the title on the activity page)
- Calendar descriptions
(To name a few, I am sure there are more examples)

I attach a few screenshots of the custom css we created to improve this manually (within the .scss file for Boost Campus), maybe these adaption can be used in order to prepare a configurable solution that also lets admins decide which colour to use. Since we're on dark grey as brand colour we were quite happy to at least add some colour to the overall appearance that's more a funeral home than a learning environment.

Best regards
Wiebke (Hochschule Hannover)

3.11 Dashboard Course overview
![grafik](https://user-images.githubusercontent.com/72548805/205011482-b0b9945f-5cf2-4447-8fd8-a1e970c562cd.png)

3.11 Atto plain text
![grafik](https://user-images.githubusercontent.com/72548805/205011917-0177b446-4f66-4017-812e-a4351808bea9.png)

**Comment by dbnschools** [comment]
Some other ideas I will be putting into the LearnR child theme is the ability to select section styles where from a drop down a user can drastically change the way the course is presented to the user.  It simply includes some small styling changes pre-packaged for the site admin to choose from.  

I am also implementing more options for use of background/course images so that a user can create a more styled combination of page background and course header background.  I might use a similar drop down setting so that the site admin can just select the option they want and the theme will load all necessary changes.  

Three things I think Boost Union would greatly benefit from but could also be where child themes help enhance the core Boost Union: 
-  More options for the login page so that the site admin can create a customized login page when you force users to login.
- Home and Course Category course tiles.  The Moodle default listings are terrible.  I do see a pull request for this derived from the Moove theme and I would encourage to implement it.  
- A customized course enrollment page.  Design a page made to sell the course content if someone is just browsing courses.  This is needed not just for for-profit organizations but also for staff development, trainings, and other uses.  This would be a feature that is very scarce for Moodle.  This would be a most desirable feature for a theme that I have not seen done well yet.

**Comment by wiebkemueller-hsh** [comment]
As many of the above mentioned ideas have partly been introduced into boost or boost union, this ticket will be closed. please open separate issues (feature requests) if single points haven't been solved yet.
