### ISSUE TITLE
Bug: Wrong definition in post.scss in plugin version 2023010505

### ISSUE THREAD

**Issue by BennoKind** [moodle-an-hochschulen/moodle-theme_boost_union#244]
In the file scss/boost_union/post.scss (line 494) is a wrong definition of a background-color:

```
/* Add a more solid background color so that the title remains readable. */
.card-header {
    background-color: rgb(255, 255, 255, .8);
}
```
This should be: rgba(255, 255, 255, .8);

**Comment by lucaboesch** [comment]
You're right.
Sorry I didn't notice that when peer reviewing.

**Comment by abias** [comment]
Thank you @BennoKind for highlighting this SCSS glitch!
Interestingly, the SCSS compiler already notices the alpha channel and compiles a proper `rgba` instruction for the browser. That's why I didn't spot this glitch during development, sorry...

I have quickly fixed this in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/1790e5d0682f8158147fe15055bc196c58b13fde.

Cheers,
Alex
