### ISSUE TITLE
Improvement: Course category breadcrumbs in course header

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#284]
Some miss the course category breadcrumbs in course header back since they are arguably a great way to navigate.
https://moodle.org/mod/forum/discuss.php?d=433872
https://tracker.moodle.org/browse/MDL-77934

<img width="609" alt="image" src="https://user-images.githubusercontent.com/377279/233311442-ee70ed59-a2dd-45f8-9d48-480834956955.png">

This is to bring them back, upon configuration, in Boost Union.

**Comment by abias** [comment]
This was solved in #285

**Comment by danowar2k** [comment]
Why is this setting necessary with today's Moodle 4.1-4.3 code?

If you want categories in the course breadcrumb, you could enable **navshowcategories** for admins/non enrolled people and **navshowmycoursecategories** for enrolled users.
The last category isn't linked and courses with only one parent category don't display the breadcrumb at all because it's the only item in it, but is that the reason?
