### ISSUE TITLE
Overwrite Modules purpose 

### ISSUE THREAD

**Issue by goggo24** [moodle-an-hochschulen/moodle-theme_boost_union#288]
Because we do not agree with every classification of the purpose or because some third-party plugins do not currently support it, we've implemented an adminsetting, to overwrite the purpose of plugins. In our child theme all installed modules are listed with their default purpose. If a plugin hasn't set a purpose "other" is default.  As admin now you have the possibility to overwrite the purpose without any need of patching the plugin himself. 

![grafik](https://user-images.githubusercontent.com/16721900/234923432-6165d7ac-da2e-46d4-9150-862c72843a55.png)

If you think, it's helpful - we can make a PR in the next weeks to integrate it in boost union.

Regards, Eva K (AMC)

**Comment by abias** [comment]
This was solved in #308 as a MoodleMootDACH DevCamp result :)

**Comment by tjettmers** [comment]
Hi @abias and @goggo24,
we just updated Boost Union and maybe there is an unnoticed issue. 
If I change the purpose of an activity, everything looks fine on the coursepage:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/60962776/88e26802-c6a4-4b09-943b-9f3cdc4a2fa8)
But if I click on the (purpose-changed) activity, it is displayed with the old color:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/60962776/9c4edb64-e77d-4116-bb11-aaea909c4bdc)

Regarding the source of the code, I am not sure, if this already has been a problem in Vienna or the problem comes with the integration into Boost Union "core".

**Comment by goggo24** [comment]
@abias how shall we proceed? The commit on 26.05 and 29.05 should fix the problem

![Screenshot from 2023-06-22 16-19-14](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/16721900/512dad51-72f5-4156-b654-104f43b7adbb)

**Comment by abias** [comment]
Hi @tjettmers and @goggo24 ,

thanks for raising this additional issue and for providing a bugfix. However, this issue is closed now.
But I also think that this issue is already reported on #318.

I will transfer your bugfix to this issue and will try to solve it there.

Thanks,
Alex
