### ISSUE TITLE
Feature: More block regions

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#30]
This has an overlap with #6, but goes far beyond that issue:
Being able to customize the Moodle pages is a goal of this theme and many things can still be done today with blocks.

We want to:
* Add several additional block regions to the Moodle page, basically everywhere where (information or functionality) blocks should or could be added
* Control the visibility of these block regions with a capability for each region. This way you can restrict the visibility of blocks to certain roles or to admins only without relying on visibility support in the blocks.
* Control the editability of these block regions with a capability for each region. This way you can provide blocks to Moodle users but can avoid that teachers modify the blocks within their courses.

**Comment by stefanscholz** [comment]
Hi @abias,

as discussed recently, we'd like to work on this issue. We propose the following scope:

### Block regions

- Block region „top“ — directly above content (boxed)
- Block region „header“ — directly below the navbar (full width)
- Block region „left“ — left of contents (like in classic)
- Block region „right“ — right of contents (like in classic)
- Block region „bottom“ — below content (boxed)
- Block region „footer left“ — above boost union footer, 33% percent if all three are used, 50% if only two are used, 100% if only one is used
- Block region „footer center“ — see above
- Block region „footer right“ — see above
- Block region „off canvas“ — see mockup; a region which is hidden off canvas and its visibility can be toggled using a new icon in the navbar to the far right

Please note that "content" refers to the course contents (sections + activities) on course pages and the main content block region outside of courses.

### Requirements
- For each block region, a dedicated capability shall be added to control who can see the block.
- For each block region, a dedicated capability shall be added to control who can edit the block.
- For the block region left and right, the admin should be able to define the width of the block region.
- For the block region left and right, the admin should be able to define if 
  - the block region is positioned next to the main content area (and, if the screen is big enough, some space between the block region and the end of the browser window might exist) OR
  - the block region is positioned next to the end of the browser window (and, if the screen is big enough, some space between the block region and the main content area might exist)

### Mockup
https://preview.uxpin.com/b09e36872e77fb71e712d1762f44e5d6e5b08f84#/pages/158695259/simulate/sitemap?mode=i

### Please note
In order to keep the "first issue" simple, I would like to add the additional block regions we discussed in the second step. For transparency, these were:
- Instead of one block region left, create left top and left bottom, to provide a "safe" block region for admins which others can't override to ensure consistency across courses
- Instead of one block region right, create right top and right bottom, same reason as above
- Instead of one block off canvas block region, create three: off canvas left, center and right, to be consistent with the footer

**Comment by stefanscholz** [comment]
![1-Dashboard-158695218-1663322914](https://user-images.githubusercontent.com/3414705/192944992-37911caa-248d-4693-87ca-d1e9484cf9fd.png)
![2-Course-158695990-1663325357](https://user-images.githubusercontent.com/3414705/192945000-85ae1877-8bef-4bbd-aaf5-b8ce8aa53a24.png)
![3-Frontpage-158699001-1663329967](https://user-images.githubusercontent.com/3414705/192945004-6ccbb63d-51e8-47b5-9d0d-1e58bdd8e268.png)

**Comment by abias** [comment]
Hi @stefanscholz ,

thank you very much for taking care of this issue!
I have just added you as assignee to make clear that you are working on it now.

Regarding the specification, I think it's spot-on and you are ready to start with the implementation.

> In order to keep the "first issue" simple, I would like to add the additional block regions we discussed in the second step. For transparency, these were:
>    Instead of one block region left, create left top and left bottom, to provide a "safe" block region for admins which others can't override to ensure consistency across courses
>    Instead of one block region right, create right top and right bottom, same reason as above
>    Instead of one block off canvas block region, create three: off canvas left, center and right, to be consistent with the footer

I agree with this approach for the first two items. We just need a follow-up issue created when this issue here is closed to avoid forgetting about these improvements.

Regarding the third item, I would love to see it implemented already in the first iteration if you can do it in any way. My reasons are that we would have the consistency of the canvas block region with the footer right from the start and, additionally, admins who want to add more than one block into the canvas region won't have to rethink when the second iteration is shipped finally.

**Comment by stefanscholz** [comment]
@abias — as discussed this morning, we'll include the additional off canvas block regions right now and deal with the other two additional block regions later. 

Development started.

**Comment by stefanscholz** [comment]
As discussed today, it is proposed to improve the implementation of the block regions as follows:

- Move the global settings category "Block region" into the existing global settings category "Feel" in the blocks tab.
- Add a setting for each block region to enable/disable the block region, i.e. "Block Region Left" — checkbox — disabled by default; only display the block region if the corresponding setting is enabled; by default, no block region shall be enabled
- Add a help text for each setting displayed below the settings with the following text: "This setting determines wether the block region <name of block region> shall be available. 
- When editing is turned on, the new off canvas drawer shall not be displayed; its visibility shall be toggled by the 9 dots menu; when it is visible, it shall be displayed above the normal site content (like it is currently in editing mode), with the same background color (#f8f9fa) that it currently has  (when editing is turned off)
- The block-region-top shall have a dotted border without rounded edges and be positioned directly below the navbar.

**Comment by abias** [comment]
This has been finally solved in #118 :)
