### ISSUE TITLE
Fixing missing active class in menu items made with Boost's custommenuitems

### ISSUE THREAD

**Issue by haw-fachadmin** [moodle-an-hochschulen/moodle-theme_boost_union#384]
In Boost theme, there's an annoying issue: the links of menu items made with Boost's custommenuitems field in theme settings don't get an `active` class assigned to them.
_Notice: This matters if you have multiple custom horizontal menu items instead of putting them into a dropdown._

Would be great to get that fixed in Boost Union!

**Comment by wiebkemueller-hsh** [comment]
Hello HAW-Fachadmin, 

thank you for posting this. I believe there is also the necessity to discuss this regarding the smart menu feature inlcuded in Boost Union. Menu items created with the smart menu also do not get an active class, but this might be for a reason. 

E.g. I can create a external link, in this case an active link is of no use. 
E.g. I can create a menu with submenus that are only displayed after clicking on the top categorie of the menu.

I marked this "discussion needed". 

Regards from H
Wiebke

**Comment by wiebkemueller-hsh** [comment]
assigned to yvonne for requirements check

**Comment by whuml** [comment]
Identified Issue as Boost Union Bug:
moodles custommenuitems "activ" (underline) works fine, as long, as "Boost Union Smartmenue" is not activated.
Activating or unhiding (show) "Smart Menus" causes that active custommenuitems are not underlined anymore.
Smartmenueitems are not underlined as activ as well/ in gerneral. 
Instead "home" is underlined as active :-(

**Comment by wiebkemueller-hsh** [comment]
Hello @haw-fachadmin,

we'll close this ticket. The behaviour you described seems to be fixed in Boost (just verifyed on the official mount orange school testsystem). There are other issues related to the missing highlighting of the smart menu items that are being discussed in #715 
#620 .

Regards on behalf of the BU-team!
Wiebke

**Comment by abias** [comment]
Hi all,

I had to see that this issue was solved already upstream in Moodle Core in https://tracker.moodle.org/browse/MDL-77732 for Moodle 4.3 and upwards. And this issue here would have been void if we would have merged PR #648 earlier which adopts these changes to Boost Union. 

#648 will now be integrated soon and will be backported to Moodle 4.4 and 4.3.
It will _not_ be backported to 4.1 due as it would require more work. This means that this issue will remain unfixed on 4.1.
