### ISSUE TITLE
Bug v4.1-r10: Installation and Upgrade Mustache errors

### ISSUE THREAD

**Issue by luiggisanso** [moodle-an-hochschulen/moodle-theme_boost_union#390]
Hi team

I would like to test the new smartmenus features, but I have a bug during update and/or installation...

Prerequisites:
- Moodle 4.1.5
- PHP 8.0.30
- MariaDB 10.6.15

Steps:
- I download the latest version of the theme for 4.1 (version 4.1-r10)
- I visit the new settings page without making any changes
- I go to Appareance then Theme selector
- I choose boost_union

And I get an error:
```
Exception - Too few arguments to function navigation_node::title(), 0 passed in [dirroot]/lib/mustache/src/Mustache/Context.php on line 219 and exactly 1 expected
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 580 of /lib/navigationlib.php: ArgumentCountError thrown
line 219 of /lib/mustache/src/Mustache/Context.php: call to navigation_node->title()
line 99 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
[...]
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_ea645d3886dcb59878926d3f3805f6bd->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 198 of /theme/boost_union/layout/drawers.php: call to renderer_base->render_from_template()
line 1477 of /lib/outputrenderers.php: call to include()
line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 54 of /theme/index.php: call to core_renderer->header()
```

Is it a real bug or just me ?

PS. I have the same bug with the 4.2-r1 version in a moodle 4.2.

Thanks.

**Comment by luiggisanso** [comment]
Same issue with 4.1-r11 :-(

**Comment by abias** [comment]
Hi @luiggisanso ,

I am very sorry for that. That should not happen. I have hidden the v4.2-r1, v4.1-r11 and v4.1-r10 release in the Moodle plugins repository until I have the time to check if this is a fatal issue.
Please stay tuned.

**Comment by abias** [comment]
Hi @luiggisanso ,

I have a rough idea what this error is about, but I was not able to reproduce it at all. I tried a fresh installation of Boost Union as well as a theme update from v4.1-r9 to v4.2-r1 on Moodle 4.2.

May I ask you for more details:
* On what page / what URL does this error appear?
* Did you make _any_ settings in Boost Union or are all settings left at their defaults?
* You write that this happens during "update and/or installation". Is this really true, I mean does it happen on a fresh installation as well?
* If you are doing an upgrade, do you upgrade from any pre-release / development version of Boost Union?
* Does this error persist of you clear the mustache caches (if the web GUI is completely broken: via CLI)?
* Do you run any grand-child theme of Boost Union or is this pure Boost Union?

Meanwhile, as I can't reproduce the error, I have re-shown the affected releases and hope that this is any local issue of yours.

Thanks,
Alex

**Comment by slaudel** [comment]
Hi,

same here.
We were upgrading from commit 3f2c7a754f9d24a6170eceb7485b53a5e5e6dc40 to the latest MOODLE_401_STABLE.
For us it happens when accessing any page.
Boost union was installed and we had certain things configured.
I don't know if it happens on a fresh install, as we only tried it on our test system.
Clearing caches helps calling start page, but after login the error persists.
For us, we have pure boost_union.

Regards
Sven

**Comment by abias** [comment]
Thank you, Sven.

I found the culprit now.

Long story short:
This issue is a regression of #385 which adopted Moodle core changes from MDL-78656 into Boost Union.
During this adoption into Boost Union, it was overseen to raise the minimum required Moodle core version for Boost Union at the same time. I am really sorry for that!

I will publish an updated Boost Union release instantly. This should fix the issue for you.

If you intend to use this release of Boost Union then, please update Moodle core to the latest Moodle core 4.1.5+ / 4.2.2+ or wait some more days for 4.1.6 / 4.2.3. Thank you for your understanding.

Cheers,
Alex

**Comment by abias** [comment]
You're welcome, Luiggi!
And sorry again for the hickup!
