### ISSUE TITLE
The scroll spy does not work in Moodle 4.3

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#420]
Dear developers,
since our update to Moodle 4.3 the scroll spy does not work anymore. When you toggle the edit mode the page goes up to the top.
Best regards,
Ralf

Ralf Krause
moodleSCHULE e.V.

**Comment by abias** [comment]
Thank you, Ralf, for reporting this issue.
I am currently preparing the 4.3 upgrade of Boost Union and have just fixed this issue in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/7da8096ebf8c84b8140ff7e60a90a55555900200. It will be part of the 4.3 which will be published soon.

**Comment by alma-ohrankammen** [comment]
Hello,

We have recently updated to Moodle 4.4 and encountered the same issue with the scroll spy not working, similar to the problem reported by Raf Krause in version 4.3. The scroll spy functioned correctly in our previous version 4.3.

When pressing the "Save and return to course" button, the page navigates to the beginning of the course home page instead of returning to the specific activity, as expected.

Best regards,
Alma Ohrankämmen
