### ISSUE TITLE
Smart Menus: search of cohort in restrict visibility by cohorts doesn't work properly

### ISSUE THREAD

**Issue by ppv1979** [moodle-an-hochschulen/moodle-theme_boost_union#462]
We have 5000+ cohorts in our Moodle. When I've tried to "Restrict visibility by cohorts" for one of the smart menu the list "By Cohort" shows only first 25 cohorts from the system cohorts and search only in this list of 25.
 It looks like it doesn't perform query to the server to fetch other cohorts according to the search query. 

Moodle 4.1.6+, Postgres 13.11.

**Comment by whuml** [comment]
Dear @ppv1979 
could you give us some more information about the bug report and the prerequisite ref your cohort use (5000+)? 
This would help to reproduce and fix the problem.
Thank you!

**Feel free to use this template:**

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

    OS: [e.g. iOS]
    Browser [e.g. chrome, safari]
    Version [e.g. 22]

Smartphone (please complete the following information):

    Device: [e.g. iPhone6]
    OS: [e.g. iOS8.1]
    Browser [e.g. stock browser, safari]
    Version [e.g. 22]

Additional context
Add any other context about the problem here.

**Comment by ppv1979** [comment]
1. Go to 'Smart Menus'
2. Click on 'Create Menu' button
3. Fill in field 'Title' (enter any text)
4. Open drop-down list 'Menu location(s)' and select 'Main navigation'
5. Open 'Restrict visibility by cohorts' accordion

Then you can try to select cohort in different ways:
Test  #1:
6. Open drop-down list 'By cohort', scroll it and select any cohort from the list, the list contains only 25 cohorts.
Everything works fine, as it should.

<img width="648" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5909987/73ab237e-6a6f-49f8-8e27-fc8dc18b6cef">


Test #2:
6. Open drop-down list 'By cohort', put the cursor and try to enter a part of the name of one from that 25 cohorts that are in list.
Everything works fine, as it should.
<img width="645" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5909987/6aef8417-479f-4332-8aee-1376616dc42e">


Test #3:
6. Open drop-down list 'By cohort', put the cursor and try to enter a part of the name that are not part of the names of the 25 cohorts that are in list, but existed in the system. For example, I have a lot of cohorts that starts with '2023'. Nothing is found. Bug.
<img width="758" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5909987/ceb711e8-984c-4b85-a0ea-a47e6a45956a">

**Comment by ppv1979** [comment]
Hi,@wiebkemueller-hsh! 

Have you managed to reproduce this bug?

Regards,  
Pavel.

**Comment by cjbsdigitallearning** [comment]
This is impacting us also on v4.3-r8 currently. Same as above, only the first 25 cohorts are listed in the drop down. We only have around 200 system cohorts total

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/88316752/24a042a5-98cb-4188-9a64-601648c96047)

On searching for "students_" nothing is found, I suspect it is only searching the first 25 that are initially shown in the dropdown rather than all system cohorts. Showing only 25 in the search results is fine, as long as it a max of 25 results from the search string entered.

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/88316752/39bc41b7-ffc9-4def-ae29-518f6dd0170b)

**Comment by abias** [comment]
Hi all,

I am really sorry that this bug remained unhandled for so long as it was really easy to fix. I just submitted a PR on #615 which should be integrated soon.

Cheers,
Alex
