### ISSUE TITLE
Scrolling freeze on mobile 

### ISSUE THREAD

**Issue by Liberty8789** [moodle-an-hochschulen/moodle-theme_boost_union#463]
Scrolling freeze on mobile

**Comment by wiebkemueller-hsh** [comment]
Dear Liberty8789,
could you give us some more information about the bug report? This would help to reproduce and fix the problem. 
Thank you!

Feel free to use this template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by Liberty8789** [comment]
Hi,

Thank you for your reply.

Go to 'Profile page or dashboard'
Click on '....'
Scroll down to 'scroll on mobile'
See error The site freeze until you click may be a button or back button.
Enrollment method in course administration grey out

**Comment by whuml** [comment]
Hi @Liberty8789 
I tried to reproduce any scroll freeze error.
I tried it with android mobile app and on android mobile firefox.
Everything works fine for me! I could scroll everywhere at every place ...
But - I couldn't find your "Click on '...' ->  'scroll on mobile'

Perhaps you could provide some of these:

- screenshot(s)
- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Mobile App Version
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]
- Moodle Version
- Boost Union Version 

Sorry for further inquiry ...

Brgds Wolfgang

**Comment by Liberty8789** [comment]
Thank you for reaching back on this. I later tried it out with other theme.
I discovered it is not the theme but the server related issue. Thank you.

**Comment by whuml** [comment]
Hi @Liberty8789 
Thank you for your final reply
best regards
