### ISSUE TITLE
Problems with theme 

### ISSUE THREAD

**Issue by paulUDIS** [moodle-an-hochschulen/moodle-theme_boost_union#522]
My apologies I am reopening  with a new issue from a previous issue which I thought had been resolved.(#510) 
 What prompted the issue was that moodle looked for upgrades and it said
there was one for boost union but no matter what I did it wouldn't do
anything. So I thought that I would step install because there were lower version so I started at the next one up, 
I deleted the theme and it reverted to the boost theme and then reinstalled the boost union plugin I had before. This is the version of
boost union theme. (theme_boost_union_moodle41_2023010530)  As far as I could tell it installed perfectly  (theme_boost_union_moodle41_2023010530)
Now I am getting this error when I select the theme. 

Exception - Too few arguments to function navigation_node::title(), 0 passed in [dirroot]/lib/mustache/src/Mustache/Context.php on line 219 and exactly 1 expected

And that is it. The site is locked.
Paul

**Comment by paulUDIS** [comment]
I tried this command from the command line while logged into my server and It cannot open it. 
/home/admin/web/learn4life.heliohost.us/public_html/admin/cli$ sudo php admin/cli/cfg.php --name=theme --set=boost
Could not open input file: admin/cli/cfg.php

**Comment by wiebkemueller-hsh** [comment]
Dear @paulUDIS 

can we maybe redirect the discussion to the support forum? There might be other people that have come accross this. You can actually always change to the boost theme via https://moodle.org/mod/forum/discuss.php?d=452129.

In case we're looking at a bug, we would need exact steps to reproduce in a test system because we haven't come accross the described behaviour, yet. 

One more question, are you sure that the deinstallation of the theme had worked properly according to the instruction Alex gave [here](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/510#issuecomment-1868222868)? Just to avoid the problem is caused by conflicting theme "remainers" during the whole process.

Regards
Wiebke

**Comment by paulUDIS** [comment]
I tried to follow the directions but for some reason it would not let me
uninstall the theme. I was using the terminal to issue commands and even
with sudo it would not work. I ended up ftp in and deleting the folder. It
is still in the system though because it still notices me about updates.
Sure if you want to repost it. The community might come up with some
suggestions. Would you like me to do it?
Paul

**Comment by wiebkemueller-hsh** [comment]
Hi @paulUDIS 

I think it is always a good idea to ask these kind of support questions with a clear description of what you did in a greater community, somebody might understand your local settings. One thing is for sure though, by only deleting the folder via ftp the theme clearly isn't properly removed and this might cause problems in the following installation process.
