### ISSUE TITLE
Activity Navigation: Wrong positioning of arrow in next section link

### ISSUE THREAD

**Issue by v-r-n-a** [moodle-an-hochschulen/moodle-theme_boost_union#536]
If _theme_boost_union | activity navigation_ is enabled and you visit a section page in a course with the course format _Topics: Show one section per page_, the arrow in the link to the next section is in front of the section name (_see screenshot_). 

The arrow should appear after the section name (as on activity pages with a link to the next activity).  -> On the screenshot after _Abschlussreflexion & Evaluation_

![BU_section-navigation-icon](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/151947222/8c91c80f-44cf-40ba-9a75-b84de7197607)

Moodle Version 4.1.8 (Build: 20231222)

**To Reproduce**
1. Enable activity navigation in administration
2. Create a course with course format _Topics: Show one section per page_ and add at least 4 sections (0, 1, 2, 3).
3. Visit section page 2 (i.e. .../course/view.php?id=182&section=2)
4. Look at the link to the next section: the arrow is in front tof the link name
5. (Optional: Create at least 3 activities and visit the 2nd activity. Compare the next activities link (arrow behind name) with the next section link)

_Edited 2023/01/08:_ With course format _Weeks: Show one section per page_, the behavior is the same.

**Comment by abias** [comment]
Hi @v-r-n-a , many thanks for reporting this issue.

I had a look to see what's going on here and can now say:
* This issue is only an issue if the `theme_boost_union | activitynavigation` setting is set to yes. In this case, the `$PAGE->theme->usescourseindex` flag is set to false which causes Moodle core to assume that the theme does not use a course index and renders additional navigation elements.
* The `theme_boost_union | activitynavigation` setting was initially meant to show the activity navigation elements between individual activities. But I had to see now that Moodle core also respects this setting to decide if additional section navigation elements should be shown when the course format is configured to be used as single section per page.
* The activity navigation and the section navigation are rendered by different methods. While the activity navigation has the arrow on the right side, the section navigation has not (as reported here).
* It is even more complicated as there are two section navigation widgets: 
<img width="1293" alt="grafik" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1092118/3b4bc4c7-04d5-4482-826c-1dd875609a54">
The upper one is rendered with the core_courseformat/local/content/sectionnavigation mustache template and the lower one is rendered with the core_courseformat/local/content/sectionselector mustache template.

While Boost Union _could_ overwrite these mustache templates and place the arrow on the opposite side, my gut feeling is that we should not do that in Boost Union.

@v-r-n-a , I would rather encourage you to report this glitch on tracker.moodle.org for Moodle core. If Moodle core fixes it, Boost Union will automatically adopt the change.

Furthermore, there are also the open issues #586 and #587 from you. There, additional presentation settings for the activity navigation and the settings navigation are proposed.
If we introduce presentation settings there, we can piggypack the arrow glitch fix on these settings there.

The only thing I will implement now is an enhancement of the description of the  `theme_boost_union | activitynavigation` setting now.
