### ISSUE TITLE
Make block regions available for more page layouts

### ISSUE THREAD

**Issue by stefanscholz** [moodle-an-hochschulen/moodle-theme_boost_union#543]
Currently, some block regions cannot be used on all page layouts.
It is proposed enable all applicable block regions for all applicable page layouts, at least for the incourse page layout.

@abias  — here's the issue as discussed.

**Comment by abias** [comment]
> What are the plans for the other layouts?

For the incourse and coursecategory layout, it was ok for me to offer all block regions in the end.
For the remaining layouts which still get only a subset of the existing additional block regions, I would be looking for real-world use cases before we clutter the UI with (useless) block regions.

If you have such real-world use cases, please create a new issue to handle them as this issue here will be closed as soon as #545 is merged.
