### ISSUE TITLE
Wrong highlighting of active menu item in the main menu

### ISSUE THREAD

**Issue by HsH-Wolf** [moodle-an-hochschulen/moodle-theme_boost_union#620]
**Describe the bug**
If I place a static page like help.php in the main menu and then klick on this menu item, "home" is marked as active menu item instead of the actually visited page. (referres to #384 )

**To Reproduce**
- as an admin create a new menu item in the main menu (e.g. as custom menu item via theme settings or as static inline smart menu item)
- after saving these settings go to dashboard (now dashboard is marked as active menu item)
- now go to the new menu item (now home is marked as active menu item)

<img width="849" alt="bug-highlight" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/56588802/73202d60-1a5d-4453-b50f-db982ad957f8">

**Comment by kaaermes** [comment]
is not fixed!

as you can see in this screenshot: the active page ist "smart help" but "home" ist highlighted instead

<img width="880" alt="Bildschirmfoto 2024-10-08 um 13 04 08" src="https://github.com/user-attachments/assets/38670ea9-5203-48c2-9aef-bfa4a431cb0e">

**Comment by abias** [comment]
Hi all,

I had to see that this issue was solved already upstream in Moodle Core in https://tracker.moodle.org/browse/MDL-77732 for Moodle 4.3 and upwards. And this issue here would have been void if we would have merged PR #648 earlier which adopts these changes to Boost Union. 

#648 will now be integrated soon and will be backported to Moodle 4.4 and 4.3.
It will _not_ be backported to 4.1 due as it would require more work. This means that this issue will remain unfixed on 4.1.
