### ISSUE TITLE
show full breadcrumb (including course title) when displaying section page (and also further down on activity level)

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [moodle-an-hochschulen/moodle-theme_boost_union#681]
As of 4.4 moodle introduced clickable section titles that are landing on section pages
https://sandbox.moodledemo.net/course/section.php?id=15

Accordlingly the breadcrumb behaviour in boost core was changed and the course short title is displayed in the breadcrumb
![grafik](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/72548805/d017d361-d652-459e-8ed9-691dbfddca04)

this has to be reviewed for boost union, as currently (citing from the forum thread):

- "In Moodle 4.4 if I click on section, there is no way to back to the course start page using breadcrumb, only way out to the course category list and enter the course again, because the course name is missing from breadcrumb. In the Boost theme course name is in breadcrumb so I can go back, but in Boost Union instead course name there is always only the course category, no matter how "Display the category breadcrumbs in the course header" is set.
- Entering the forum or other activities, the breadcrumb shows correctly: category / course name / activity name. I want to see the course name in breadcrumb when I'm entering into the one of the sections, by clicking on section title introduced in Moodle 4.4. When I'm on the main page the course name can stay hidden."

The following issues can be seen as related to this
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/594
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/572

Depending on the time there is to fix this, we could think of an option, to optionally display something even shorter than the course title. Since the breadcrumb won't be sticky (see alternate desired solution to this in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/654) the course title is soon to be expected to permanently remain visible in the course index no matter the scroll status.

Thank you for considering!

**Comment by abias** [comment]
Hi all,

this issue has now been fixed for Moodl 4.4 in 06dc95e472298e212d7a1144082a50c7eff53fe3.
This commit is located in the [upgrade-404](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commits/upgrade-404/) branch which will be merged in the main branch as soon as the whole Moodle 4.4 upgrade work is done.

Please note that this issue was just about a blocker for the 4.4 release. 
The linked issues #594 and #572 and #654 are all related but will be handled separately and independently from the Moodle 4.4 upgrade.

Cheers
Alex
