### ISSUE TITLE
Improvement: Smart Menu - List settings: allow list of courses of "other users"

### ISSUE THREAD

**Issue by AntonT76** [moodle-an-hochschulen/moodle-theme_boost_union#698]
Hi,

we are using a Moodle role "Coordinator" which is set in course categories and will be inherited to all courses in this category. Users with this role will be shown in courses as "other users" - so they don't see these courses in the course overview or will not be listet as course participants.

We try to make this courses visible in a list for users, which are part ot the "Coordinator"-role. If we create a Smart Menu and set a menu item, which is set to "Restrict visibility by roles" - "Coordinator", the list of courses is empty. It should be possible that the Smart Menu should also list courses of roles which are set as "other users".

thanks & best regards
Anton

**Comment by wiebkemueller-hsh** [comment]
Hi @AntonT76 Anton, 

thank you for reporting this. We'd have to talk this through as an enhancement I guess. The persons are not technically enrolled in the courses. 

In our case it would not make sense to create a single list for the supporters (as we call it), since this list would be veery long and it is far quicker to search for the course via Dashboard/course search. But this might be different in your use case. 

Maybe the following setup would be helpful for you, we applied this, and it is a little short cut:

We solved this by creating cohorts of the supporters (by faculty) and by providing the (limited) group of people with the support role a smart menu containing the links to the faculty course categories they are supporting.
Restrict visibility by cohorts (support)
Menu item type: Static
Access rules for menu items: By cohort (again by faculty)

Regards
Wiebke

**Comment by AntonT76** [comment]
Hi @wiebkemueller-hsh 

thanks for the solution. We will have a look at it. In our case, it would be better to add an additional filter in the "Course Overview" block that filters by role (e.g. Teacher, Student, Coordinator). However, this should generally be available in Moodle Core.

br, Anton

**Comment by wiebkemueller-hsh** [comment]
Hey Anton, will close this: As for now we are concentrating on bug fixes and maintenance of existing features in order to keep the limited resources focused on adhering to the moodle update cycle. Regards Wiebke
