### ISSUE TITLE
 Smart menu: highlight static internal links in the main menu

### ISSUE THREAD

**Issue by HsH-Wolf** [moodle-an-hochschulen/moodle-theme_boost_union#715]
If a static internal link is added to the main menu as smart menu, there is no highlighting as active page.

**Steps to reproduce:**
- Add a smart menu to the main navigation (inline, list)
- Add one item to this menu: an internal link (e.g. to a course) as static inline item 
- click this menu item and see, that there is no highlighting

**Comment by HsH-Wolf** [comment]
referres to #620 und #384

**Comment by kaaermes** [comment]
<img width="880" alt="Bildschirmfoto 2024-10-08 um 12 56 23" src="https://github.com/user-attachments/assets/bbc5a9c2-5f61-4dbb-bce3-22201b2dc696">
<img width="880" alt="Bildschirmfoto 2024-10-08 um 12 56 39" src="https://github.com/user-attachments/assets/dedc6213-c6e5-4c11-82d7-8cefddf1afd6">

as you can see in the second screenshot there is no active navigation marker for the active smart menu item "Internal link"

**Comment by abias** [comment]
Hi all,

I had to see that this issue was solved already upstream in Moodle Core in https://tracker.moodle.org/browse/MDL-77732 for Moodle 4.3 and upwards. And this issue here would have been void if we would have merged PR https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/648 earlier which adopts these changes to Boost Union.

https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/648 will now be integrated soon and will be backported to Moodle 4.4 and 4.3.
It will _not_ be backported to 4.1 due as it would require more work. This means that this issue will remain unfixed on 4.1.
