### ISSUE TITLE
Smart menu critical error when a Cohort used as restriction of a menu item is deleted

### ISSUE THREAD

**Issue by cjbsdigitallearning** [moodle-an-hochschulen/moodle-theme_boost_union#737]
**Describe the bug**
v4.3-r15 (2023102042)
Moodle 4.3.8 (Build: 20241007)

We experienced this today. An admin deleted a cohort that had been used along with others to restrict a menu item.. This resulted in a critical error that prevented users form accessing the site post login.

Our 3rd party support team had to do a backend fix to disable the menu containing the item with the issue. The error is still visible on the menu config page (/theme/boost_union/smartmenus/items.php?menu=) 

Error:
Exception - moodle_database::get_records_list(): Argument #3 ($values) must be of type array, stdClass given, called in [dirroot]/theme/boost_union/classes/table/smartmenus_items.php on line 155

**To Reproduce**
Steps to reproduce the behaviour:
0. Create a system Cohort and add a user to it
1. Create a new menu with 'Main navigation' menu
2. Create a new 'Static' menu item with the menu and restrict it to the Cohort
3. Check the Cohort restriction is working as expected.
4. Delete the system Cohort
5. See error

**Comment by cjbsdigitallearning** [comment]
This just in from our Moodle partner:

---
Looking at the database records, I can see that this menu entry does have a cohort restriction, but unlike the other items this one is encoded as an object rather than array. When this is decoded and passed to a PHP function that expects an array, it causes an exception.

My hypothesis as to why this started happening, is that when a cohort is deleted, the theme looks for menus and menu items with a cohort restriction, decodes that restriction, removes the deleted cohort if its there, and re-encodes it. This may have resulted in it being re-encoded as an object rather than an array. I will need to do some further investigation to confirm this, and provide a fix. Once I have confirmed this, I can also run a query on the production database to fix the broken menu item. I have attached a quote for this work.
---

**Comment by marxjohnson** [comment]
Some further details from me:

To Reproduce
Steps to reproduce the behavior:

    Create two cohorts, "Cohort 1" and "Cohort 2"
    In the Boost Union theme settings, create a Smart Menu
    Create an item in the smart menu, with the "By cohort" restriction set to "Cohort 1" and "Cohort 2"
    Go to Site Administration > Users > Cohorts
    Open the action menu for "Cohort 1" and select "Delete"
    Confirm deletion
    The error above is displayed.

Additional context

This is happening because when the event observer for cohort_deleted runs, it decodes the JSON array of cohorts, uses unset() to remove a key from the array, and re-encodes it to JSON. If the key removed is not the last key in the array, this converts the array from indexed to associative so the remaining values retain their original keys. When this associative array is JSON encoded, it is encoded as an object rather than an array.

To trigger this, you must have more than one role or cohort as part of the rule, and the role or cohort you delete cannot be the one with the greatest database ID (hence Cohort 1 triggers the issue in the example above, but Cohort 2 would not).

This affects menus as well as menu items, although the impact is not as severe. I have a fix incoming.

**Comment by abias** [comment]
Hi @marxjohnson and @cjbsdigitallearning ,

I am really sorry that your site broke due to this bug. The case of deleted cohorts is basically handled in Boost Union, but obviously we have missed this edge case.

I am more than grateful that you were able to investigate, reproduce and fix this bug for the community now.
You PR will be reviewed and integrated shortly.

Cheers,
Alex
