### ISSUE TITLE
Release: Take care of AMOS translation into german

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#95]
Currently, the AMOS translation into german is provided by the community only.
As this theme is built by german institutions, we should clearly define who is taking care that the german translation is always up to date and complete.

**Comment by ralf-krause** [comment]
All strings are translated yet. I hope that I am using the intended wording.

**Comment by abias** [comment]
Hi @ralf-krause ,

we are aware that you have already translated the theme into german in AMOS and we really appreciate your work!
This issue is mainly about organizational questions, particularly who will be taking care of the translations in the long run and who makes sure that the german translation is made with low latency after a theme release.

Is this something which you already do as german language pack maintainer for Moodle core or is it at least something which you would volunteer to do for this theme?

Otherwise, we will try to appoint someone from within the association to take care of these tasks.

**Comment by ralf-krause** [comment]
Hi Alex,
I‘m translating the Moodle core and a lot of plugins since 2003 or 2004. I never had to pay for Moodle but I used it for my work at school and in my workshops for teachers. 

The Moodle core theme Boost is not Perfect for me. The theme Boost Union will help to make it Vetter. So it is an important thing which I will use in my own Moodle platforms and also in my administrated platforms. So i will use every update and I will translate it for the community. Please take it as my part for your development. 
Best regards,
Ralf

Ralf Krause
moodleSCHULE e.V.

**Comment by abias** [comment]
Thank you @ralf-krause for taking care of the Boost Union translations into german in AMOS (and, of course, for all of your commitment to the whole german language pack)! It is great that we can focus on the theme development and know that you are there to do the translation work.

Against this background, I have added you as contributor to the README.md file in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/1cdc2a03b8a3e59609ec94e25bdeae7f6d3397e8

**Comment by abias** [comment]
Thank you @ralf-krause for taking care of the Boost Union translations into german in AMOS (and, of course, for all of your commitment to the whole german language pack)! It is great that we can focus on the theme development and know that you are there to do the translation work.

Against this background, I have added you as contributor to the README.md file in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/1cdc2a03b8a3e59609ec94e25bdeae7f6d3397e8
