### ISSUE TITLE
Improvement: Further hints on hidden courses

### ISSUE THREAD

**Issue by Menrath** [moodle-an-hochschulen/moodle-theme_boost_union#98]
#5 is very helpful! In the past even though we had a similar feature (Show hint in hidden courses) in our theme, some teachers still believed that creating a new topic in the notifications forum would trigger (email) notifications. It might seem nitpicky, but adding a warning automatically via `showhintcoursehidden` also on the forum page might be of use from time to time. Pull Request would be kind of ready, as I already played around with it.

**Comment by lucaboesch** [comment]
As far as I can tell, nothing can be said against a pull request!
At max, you get some feedback on how to improve or why that woudn't fit.
Be sure to cover it by a settings toggle to enable/disable this feature.
If you are a wizard you might also cover your feature by Behat tests, but don't worry if that is not your thing.
Just pull request away.

Best,
Luca

**Comment by andremenrath** [comment]
Thanks for your quick response!

As one could add an extra setting for that, at least for me it makes sense to bind it to the `showhintcoursehidden` setting. Don't you agree? But maybe it's better if I just share my draft in a PR and let's discuss it over there.

Greetings, André

**Comment by goggo24** [comment]
Hey, which version do you prefer:
a seperate aetting or include it into showhintcoursehidden? Depending on your answer we will create the PR. 
Thanks! Eva

**Comment by wiebkemueller-hsh** [comment]
Sounds very useful! As a user I'd be thankful for that feature and it would be ok to activate it within the showhintcoursehidden. 

The description could be changed to 

Hinweis**_e_** in verborgenen Kursen anzeigen

"Mit dieser Einstellung wird ein Hinweis im Kursheader **_und in der Aktivität Forum Ankündigungen_** angezeigt, solange der Kurs verborgen ist. Dies erlaubt die Erkennung des Sichtbarkeitsstatuses eines Kurses auf einen Blick, ohne die Kurseinstellungen öffnen zu müssen."

Admin-wise, what do you think @abias ?

Regards from H
Wiebke

**Comment by abias** [comment]
Hi @Menrath ,

looking at our [project board](https://github.com/orgs/moodle-an-hochschulen/projects/4), I just spotted this issue which has been in "In progress DEV" status for quite a while now, but the discussion here and in the corresponding PR #109 somehow got stale and you have closed the PR several weeks ago as well.

I would like to encourage you to rebase and revise the code which you submitted in #109 and just control the 
new hint from a separate setting (yes, you posted in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/109#issuecomment-1884539858 that you would not like to see the admin-settings page getting bloated with too many setttings, but we do). The new setting should be located just below the existing `theme_boost_union | showhintcoursehidden` setting and can be conditionally shown with `$page->hide_if` only if `showhintcoursehidden` itself is enabled as well.

I would appreciate if you could drop us a quick note if you have time to finish this contribution. Otherwise, I would remove you as assignee and put the issue back to "Ready for DEV" status.

Cheers,
Alex

**Comment by Menrath** [comment]
Hey @abias Thanks for clarifying that one! :) I should find time for this soon.

**Comment by acquaalta** [comment]
1. Thanks a lot for this improvement :-)

2. Please note that the setting description does not state that in order for showhintforumnotifications setting to work, the showhintcoursehidden setting has to be enabled too. You can say it's stating the obvious, but ironically that would undermine the existence of the new setting ;-)
