### ISSUE TITLE
Confusing config name: Brandcolor

### ISSUE THREAD

**Issue by andremenrath** [moodle-an-hochschulen/moodle-theme_boost_union#99]
### What confused me.
For me the naming of the config setting brandcolor was confusing. For my current point of view the setting group is named correctly but the single currently present field should be named `primarycolor`. As then this setting section could also have place for fields like the navbar color etc.

### Further suggestions
When using the branded function, it is not really doing what I expected it to do by its name. For example if I have a brand color like #73a832 I would not expect it to color all links that way. But for me brand would fit for button colors, or the navigation highlightings or even the navbar color etc.

![grafik](https://user-images.githubusercontent.com/99024746/195050312-c363977b-f102-4854-bff7-018271a3023a.png)

**Comment by lucaboesch** [comment]
Dear @andremenrath this is taken 1:1 from the theme Boost settings
![grafik](https://user-images.githubusercontent.com/377279/195063159-4ff4b84d-cbb4-4d08-b5e0-33029211318a.png)
So I would vote in favour of leaving that as-is, in order to avoid creating inconsistencies with the parent theme (and to facilitate the switching from Boost to Boost Union by site admins).
If you still think this should be done, maybe it would be best to create an issue in Moodle tracker or/and write about it in Moodle forums.

I'll allow myself to close this issue.

Best,
Luca
